version: '3.9'

services:
  postgres:
    image: docker.io/postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=timelapse
